name: student_application
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1 
  firebase_auth: ^6.1.2
  dotted_border: ^2.0.0+2
  shared_preferences: ^2.0.15
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  google_sign_in: ^7.2.0
  image_picker: ^1.0.7
  url_launcher: ^6.1.14    
  file_picker: ^10.3.6
  uuid: ^4.2.2
  path_provider: ^2.1.2 
  intl: ^0.20.2
  flutter_pdfview: ^1.2.5
  path: ^1.8.3
  bcrypt: ^1.1.3
 
  flutter_native_splash: 
  flutter_animate:
  google_fonts: 
  the_responsive_builder:


 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0 
  flutter_launcher_icons:



flutter:

 
  uses-material-design: true


 

  assets:
   - assets/icons/
   - assets/images/


flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/applogo.png
  android: true
  ios: true
  web: false
  android_12: 
    image_path_android_12: "assets/icons/applogo.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/applogo.png"
  remove_alpha_ios: true